# Generated by Django 4.0.3 on 2024-05-18 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='day',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='school',
            name='email',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='school',
            name='gender',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='school',
            name='month',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='school',
            name='phone',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='school',
            name='studentid',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='school',
            name='usertype',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='school',
            name='year',
            field=models.CharField(max_length=100),
        ),
    ]
